export const COUNTRIES = [
  { name: 'Turkey (Türkiye)', value: 'Turkey' },
  { name: 'Germany (Deutschland)', value: 'Germany' },
  { name: 'United Kingdom (UK)', value: 'United Kingdom' },
  { name: 'France', value: 'France' },
  { name: 'Netherlands', value: 'Netherlands' },
  { name: 'Belgium', value: 'Belgium' },
  { name: 'Austria', value: 'Austria' },
  { name: 'Switzerland', value: 'Switzerland' },
  { name: 'Azerbaijan', value: 'Azerbaijan' },
  { name: 'Saudi Arabia', value: 'Saudi Arabia' },
  { name: 'USA', value: 'USA' }
]

export const TURKEY_81_CITIES = [
  { name: 'Istanbul (34)', value: 'Istanbul' },
  { name: 'Ankara (06)', value: 'Ankara' },
  { name: 'Izmir (35)', value: 'Izmir' },
  { name: 'Bursa (16)', value: 'Bursa' },
  { name: 'Antalya (07)', value: 'Antalya' },
  { name: 'Adana (01)', value: 'Adana' },
  { name: 'Adiyaman (02)', value: 'Adiyaman' },
  { name: 'Afyonkarahisar (03)', value: 'Afyonkarahisar' },
  { name: 'Agri (04)', value: 'Agri' },
  { name: 'Amasya (05)', value: 'Amasya' },
  { name: 'Artvin (08)', value: 'Artvin' },
  { name: 'Aydin (09)', value: 'Aydin' },
  { name: 'Balikesir (10)', value: 'Balikesir' },
  { name: 'Bilecik (11)', value: 'Bilecik' },
  { name: 'Bingol (12)', value: 'Bingol' },
  { name: 'Bitlis (13)', value: 'Bitlis' },
  { name: 'Bolu (14)', value: 'Bolu' },
  { name: 'Burdur (15)', value: 'Burdur' },
  { name: 'Canakkale (17)', value: 'Canakkale' },
  { name: 'Cankiri (18)', value: 'Cankiri' },
  { name: 'Corum (19)', value: 'Corum' },
  { name: 'Denizli (20)', value: 'Denizli' },
  { name: 'Diyarbakir (21)', value: 'Diyarbakir' },
  { name: 'Edirne (22)', value: 'Edirne' },
  { name: 'Elazig (23)', value: 'Elazig' },
  { name: 'Erzincan (24)', value: 'Erzincan' },
  { name: 'Erzurum (25)', value: 'Erzurum' },
  { name: 'Eskisehir (26)', value: 'Eskisehir' },
  { name: 'Gaziantep (27)', value: 'Gaziantep' },
  { name: 'Giresun (28)', value: 'Giresun' },
  { name: 'Gumushane (29)', value: 'Gumushane' },
  { name: 'Hakkari (30)', value: 'Hakkari' },
  { name: 'Hatay (31)', value: 'Hatay' },
  { name: 'Isparta (32)', value: 'Isparta' },
  { name: 'Mersin (33)', value: 'Mersin' },
  { name: 'Kars (36)', value: 'Kars' },
  { name: 'Kastamonu (37)', value: 'Kastamonu' },
  { name: 'Kayseri (38)', value: 'Kayseri' },
  { name: 'Kirklareli (39)', value: 'Kirklareli' },
  { name: 'Kirsehir (40)', value: 'Kirsehir' },
  { name: 'Kocaeli (41)', value: 'Kocaeli' },
  { name: 'Konya (42)', value: 'Konya' },
  { name: 'Kutahya (43)', value: 'Kutahya' },
  { name: 'Malatya (44)', value: 'Malatya' },
  { name: 'Manisa (45)', value: 'Manisa' },
  { name: 'Kahramanmaras (46)', value: 'Kahramanmaras' },
  { name: 'Mardin (47)', value: 'Mardin' },
  { name: 'Mugla (48)', value: 'Mugla' },
  { name: 'Mus (49)', value: 'Mus' },
  { name: 'Nevsehir (50)', value: 'Nevsehir' },
  { name: 'Nigde (51)', value: 'Nigde' },
  { name: 'Ordu (52)', value: 'Ordu' },
  { name: 'Rize (53)', value: 'Rize' },
  { name: 'Sakarya (54)', value: 'Sakarya' },
  { name: 'Samsun (55)', value: 'Samsun' },
  { name: 'Siirt (56)', value: 'Siirt' },
  { name: 'Sinop (57)', value: 'Sinop' },
  { name: 'Sivas (58)', value: 'Sivas' },
  { name: 'Tekirdag (59)', value: 'Tekirdag' },
  { name: 'Tokat (60)', value: 'Tokat' },
  { name: 'Trabzon (61)', value: 'Trabzon' },
  { name: 'Tunceli (62)', value: 'Tunceli' },
  { name: 'Sanliurfa (63)', value: 'Sanliurfa' },
  { name: 'Usak (64)', value: 'Usak' },
  { name: 'Van (65)', value: 'Van' },
  { name: 'Yozgat (66)', value: 'Yozgat' },
  { name: 'Zonguldak (67)', value: 'Zonguldak' },
  { name: 'Aksaray (68)', value: 'Aksaray' },
  { name: 'Bayburt (69)', value: 'Bayburt' },
  { name: 'Karaman (70)', value: 'Karaman' },
  { name: 'Kirikkale (71)', value: 'Kirikkale' },
  { name: 'Batman (72)', value: 'Batman' },
  { name: 'Sirnak (73)', value: 'Sirnak' },
  { name: 'Bartin (74)', value: 'Bartin' },
  { name: 'Ardahan (75)', value: 'Ardahan' },
  { name: 'Igdir (76)', value: 'Igdir' },
  { name: 'Yalova (77)', value: 'Yalova' },
  { name: 'Karabuk (78)', value: 'Karabuk' },
  { name: 'Kilis (79)', value: 'Kilis' },
  { name: 'Osmaniye (80)', value: 'Osmaniye' },
  { name: 'Duzce (81)', value: 'Duzce' }
]

export const CITIES_BY_COUNTRY = {
  'Turkey': TURKEY_81_CITIES,
  'Germany': [
    { name: 'Berlin', value: 'Berlin' },
    { name: 'Cologne (Köln)', value: 'Cologne' },
    { name: 'Frankfurt', value: 'Frankfurt' },
    { name: 'Munich (München)', value: 'Munich' },
    { name: 'Stuttgart', value: 'Stuttgart' },
    { name: 'Hamburg', value: 'Hamburg' },
    { name: 'Dusseldorf', value: 'Dusseldorf' },
    { name: 'Dortmund', value: 'Dortmund' },
    { name: 'Essen', value: 'Essen' },
    { name: 'Bremen', value: 'Bremen' },
    { name: 'Hannover', value: 'Hannover' },
    { name: 'Nuremberg (Nürnberg)', value: 'Nuremberg' }
  ],
  'United Kingdom': [
    { name: 'London', value: 'London' },
    { name: 'Manchester', value: 'Manchester' },
    { name: 'Birmingham', value: 'Birmingham' },
    { name: 'Leeds', value: 'Leeds' },
    { name: 'Glasgow', value: 'Glasgow' },
    { name: 'Liverpool', value: 'Liverpool' },
    { name: 'Edinburgh', value: 'Edinburgh' }
  ],
  'France': [
    { name: 'Paris', value: 'Paris' },
    { name: 'Lyon', value: 'Lyon' },
    { name: 'Marseille', value: 'Marseille' },
    { name: 'Strasbourg', value: 'Strasbourg' },
    { name: 'Toulouse', value: 'Toulouse' },
    { name: 'Nice', value: 'Nice' }
  ],
  'Netherlands': [
    { name: 'Amsterdam', value: 'Amsterdam' },
    { name: 'Rotterdam', value: 'Rotterdam' },
    { name: 'The Hague (Den Haag)', value: 'The Hague' },
    { name: 'Utrecht', value: 'Utrecht' },
    { name: 'Eindhoven', value: 'Eindhoven' }
  ],
  'Belgium': [
    { name: 'Brussels', value: 'Brussels' },
    { name: 'Antwerp', value: 'Antwerp' },
    { name: 'Ghent', value: 'Ghent' },
    { name: 'Liege', value: 'Liege' }
  ],
  'Austria': [
    { name: 'Vienna (Wien)', value: 'Vienna' },
    { name: 'Graz', value: 'Graz' },
    { name: 'Linz', value: 'Linz' },
    { name: 'Salzburg', value: 'Salzburg' },
    { name: 'Innsbruck', value: 'Innsbruck' }
  ],
  'Switzerland': [
    { name: 'Zurich', value: 'Zurich' },
    { name: 'Geneva', value: 'Geneva' },
    { name: 'Basel', value: 'Basel' },
    { name: 'Bern', value: 'Bern' },
    { name: 'Lausanne', value: 'Lausanne' }
  ],
  'Azerbaijan': [
    { name: 'Baku', value: 'Baku' },
    { name: 'Ganja', value: 'Ganja' },
    { name: 'Sumqayit', value: 'Sumqayit' }
  ],
  'Saudi Arabia': [
    { name: 'Mecca', value: 'Mecca' },
    { name: 'Medina', value: 'Medina' },
    { name: 'Riyadh', value: 'Riyadh' },
    { name: 'Jeddah', value: 'Jeddah' },
    { name: 'Dammam', value: 'Dammam' }
  ],
  'USA': [
    { name: 'New York', value: 'New York' },
    { name: 'Los Angeles', value: 'Los Angeles' },
    { name: 'Chicago', value: 'Chicago' },
    { name: 'Houston', value: 'Houston' },
    { name: 'Dallas', value: 'Dallas' }
  ]
}
